apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-boot-demo
  annotations:
    github.com/project-slug: tonylinchao/spring-boot-demo
spec:
  type: other
  lifecycle: unknown
  owner: guests
